FROM ruby:2.6
RUN apt-get update -qq && apt-get install -y nodejs netcat
WORKDIR /app
COPY Gemfile* /app/
RUN bundle install --without development test --deployment
COPY . /app/
RUN chmod +x /app/wait-for
ENV BUNDLE_JOBS 8
ENTRYPOINT ["sh","/app/docker-entrypoint.sh"]
EXPOSE 3000

ENV RAILS_ENV production
RUN bundle exec rake assets:precompile
CMD ["bundle","exec","rails","server","-b","0.0.0.0"]