version: '3'
services:
  selenium:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - '5900:5900'
  db:
    image: postgres:11.3
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  rails:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "4000:4000"
    tty: true
    stdin_open: true
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
volumes:
  db-data:
  gems-cache:
