version: '3.4'
services:
  migrator:
    image: zeitnot/rails:prod
    command: ["./wait-for","--timeout=300","db:5432","--","bin/rails","db:migrate"]
    env_file:
      - .env/production.env
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: none
  db:
    image: postgres:11.3
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env/production.env
    deploy:
      placement:
        constraints: [node.role == manager]
  rails:
    image: zeitnot/rails:prod
    ports:
      - "80:3000"
    depends_on:
      - db
    env_file:
      - .env/production.env
    deploy:
      replicas: 8
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
volumes:
  db-data:
